feat: add wallet chain select
genesis-guild/ui pull request #12
Opened 2023-07-07 21:00 UTC by 6heLL66

2023-07-08 17:21 UTC, ordinaryask requested changes
add new phantom icon and SUI wallet icon or suiet idk

2023-07-08 17:21 UTC, ordinaryask commented on src/widgets/modals/selectWallet/ui/components/ChainSelect/index.tsx
> +        return <SelectItem value={option.value}>{option.label}</SelectItem>
without return?

2023-07-09 15:06 UTC, 6heLL66 commented on src/widgets/modals/selectWallet/ui/components/ChainSelect/index.tsx
> +        return <SelectItem value={option.value}>{option.label}</SelectItem>
no :)

2023-07-11 11:04 UTC, ordinaryask requested changes

2023-07-11 11:04 UTC, ordinaryask commented on src/shared/assets/icons/solana_icon.tsx
> +export const SolanaIcon = ({ ...props }: IconProps): JSX.Element => {
export from index

2023-07-11 11:04 UTC, ordinaryask commented on src/shared/assets/icons/select_arrow.tsx
> +export const SelectArrow = ({ ...props }: IconProps): JSX.Element => {
export from index

2023-07-11 11:04 UTC, ordinaryask commented on src/shared/assets/icons/eth_icon.tsx
> +export const EtheriumIcon = ({ ...props }: IconProps): JSX.Element => {
export from index

2023-07-11 11:37 UTC, ordinaryask approved these changes

2023-07-11 11:43 UTC, merged