feat: add sign in and link wallet modals
genesis-guild/ui pull request #14
Opened 2023-07-12 15:01 UTC by 6heLL66

2023-07-13 01:36 UTC, ordinaryask requested changes

2023-07-13 01:36 UTC, ordinaryask commented on src/shared/components/copy_tag/ui.tsx
> +            maxSymbols - END_SYMBOLS_COUNT,
we have a function for that
"truncate" in shared/utils

2023-07-13 01:36 UTC, ordinaryask commented on src/widgets/modals/signIn/ui.tsx
> +import { BorderButton } from 'shared/components/border_button'
pls add index.ts file for shared/components

2023-07-13 11:42 UTC, ordinaryask commented on src/shared/components/copy_tag/ui.tsx
> +            maxSymbols - END_SYMBOLS_COUNT,
rename component to camelCase, copyTag

2023-07-13 12:59 UTC, 6heLL66 commented on src/shared/components/copy_tag/ui.tsx
> +            maxSymbols - END_SYMBOLS_COUNT,
всм
схуяли

2023-07-14 09:41 UTC, ordinaryask approved these changes

2023-07-14 09:41 UTC, merged